# Generated by https://smithery.ai. See: https://smithery.ai/docs/build/project-config
FROM python:3.11-slim

WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir fastmcp google google-genai pillow

# Copy application code
COPY server.py prompts.py utils.py .
COPY examples ./examples

# Create image output directory
ARG OUTPUT_IMAGE_PATH=/images
RUN mkdir -p ${OUTPUT_IMAGE_PATH}
ENV OUTPUT_IMAGE_PATH=${OUTPUT_IMAGE_PATH}

# Start the MCP server
CMD ["python", "server.py"]
